version: "3.9"
services:
  app:
    image: myhaskell
    build: .
    container_name: app
    volumes:
      - ./chapter1:/app/chapter1
      - ./chapter4:/app/chapter4
    stdin_open: true
    tty: true
    command: bash
