services:
  app:
    image: myhaskell
    build: .
    container_name: app
    volumes:
      - ./chapter1:/app/chapter1
      - ./chapter4:/app/chapter4
      - ./chapter5:/app/chapter5
      - ./chapter6:/app/chapter6
    stdin_open: true
    tty: true
    command: bash
