name:                chapter4
version:             0.1.0.0
license:             BSD-3-Clause

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- parallel

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  chapter4-exe:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
